### PR TITLE
support for OCaml 5

### LINKED ISSUE #29: Fails to build on OCaml 5.00 trunk
In https://github.com/ocaml/ocaml/pull/10867, OCaml removed a load of deprecated functions. This prevents ocamlfind from installing:

```
#=== ERROR while compiling ocamlfind.1.9.1 ====================================#
# context     2.1.0 | linux/x86_64 | ocaml-variants.5.00.0+trunk | https://opam.ocaml.org#ffd4aedc
# path        ~/.opam/5.00.0+trunk/.opam-switch/build/ocamlfind.1.9.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make all
# exit-code   2
# env-file    ~/.opam/log/ocamlfind-93913-b17e9e.env
# output-file ~/.opam/log/ocamlfind-93913-b17e9e.out
### output ###
# [...]
# ocamlc -I +compiler-libs -opaque -g -c frontend.ml
# File "frontend.ml", line 859, characters 10-39:
# 859 |           Fl_package_base.package_users predicates1 packages1
#                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 6 [labels-omitted]: label preds was omitted in the application of this function.
# File "frontend.ml", line 1826, characters 16-29:
# 1826 |       let buf = String.create buflen in   (* FIXME: Bytes.create *)
#                        ^^^^^^^^^^^^^
# Error: Unbound value String.create
# make[1]: *** [Makefile:165: frontend.cmo] Error 2
# make[1]: Leaving directory '/home/user/.opam/5.00.0+trunk/.opam-switch/build/ocamlfind.1.9.1/src/findlib'
# make: *** [Makefile:14: all] Error 2
```

Applying the fix in the comment does indeed fix it.

### PR DESCRIPTION
**Pull request by gerdstolpmann**
Closes #29 

`String.create` -> `Bytes.create`. Works even for very old ocaml versions (tested with 4.01.0) that do not provide the bytes type.

### CODE REVIEW

**Comment by gerdstolpmann** [comment]
Please test and leave feedback!

**Comment by Sudha247** [comment]
Can confirm I'm able to install ocamlfind with this patch on `5.00.0+trunk` compiler.

**Comment by talex5** [comment]
Using `opam pin ocamlfind https://github.com/ocaml/ocamlfind.git#ef8f1fefd3dab651fa6306826b61b28d6f1686d5` it installs for me too on 5.00+trunk. It also worked with `docker run --rm -it ocaml/opam:debian-ocaml-4.02`, which is the oldest compiler provided by the Docker repository.

Note that the `dev-repo` field in the opam metadata doesn't work however: https://github.com/ocaml/ocamlfind/blob/2c3c07624c5e4e12c8963056c4cf532a54dc59fc/opam#L8

I had to use github.com instead.

**Comment by gerdstolpmann** [comment]
Thanks for the dev-repo hint, easy to fix.

**Comment by avsm** [comment]
Thanks @gerdstolpmann @talex5! This is really helpful towards developing with ocaml-5+trunk

**Comment by kit-ty-kate** [comment]
Sadly this wasn’t enough to support OCaml 5.00 today: https://github.com/ocaml/ocaml/pull/10896
```
File "fl_metascanner.ml", line 41, characters 13-25:
41 |           in Stream.lsing (fun _ -> (line, pos, Eof))
                  ^^^^^^^^^^^^
Error: Unbound module Stream
make[1]: *** [Makefile:168: fl_metascanner.cmo] Error 2
```

**Comment by kit-ty-kate** [comment]
Hopefully this should be good this time: https://github.com/ocaml/ocamlfind/pull/31

@nojb any there any more planned removal before the release that might still break ocamlfind?

**Comment by nojb** [comment]
@kit-ty-kate No removals, but a few additional deprecations: ocaml/ocaml#10924
